name: Run tournament checker
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    environment:
    description: "Environment to run tests against"
    type: environment
    required: false
jobs:
  check-tournaments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: "20.6.1"
      - run: yarn install
      - name: Check tournaments
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

        run: node src/index.js
